index:
    path: /
    controller: App\LimaBundle\Controller\LimaController::index

connexion:
    path: /connexion
    controller: App\LimaBundle\Controller\LimaController::connexion

basesettables:
    path: /basesettables
    controller: App\LimaBundle\Controller\LimaController::basesettables

genereruncrud:
    path: /genereruncrud
    controller: App\LimaBundle\Controller\LimaController::genereruncrud

supprimeruncrud:
    path: /supprimeruncrud
    controller: App\LimaBundle\Controller\LimaController::supprimeruncrud

genererunerelation:
    path: /genererunerelation
    controller: App\LimaBundle\Controller\LimaController::genererunerelation

authsecurite:
    path: /authsecurite
    controller: App\LimaBundle\Controller\LimaController::authsecurite

console:
    path: /console
    controller: App\LimaBundle\Controller\LimaController::console

swiftmailer:
    path: /swiftmailer
    controller: App\LimaBundle\Controller\LimaController::swiftmailer

uploader:
    path: /uploader
    controller: App\LimaBundle\Controller\LimaController::uploader